server:
  port:8080

#spring:
#  data:
#    maria:
#      jdbc:mariadb://localhost:3307

spring:
  datasource:
      url: jdbc:mariadb://localhost:3307/girin
      username: 'root'
      password: 'ssafy'
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop #  Application 실행 시점에 테이블을 다 지우고 가지고 있는 Entity 정보를 보고 새로 생성한다.
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
#        show-sql: true
        format_sql: true
#    database: mysql
#    database-platform: org.hibernate.dialect.MariaDB106Dialect

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace #스프링 부트 2.x, hibernate5
# org.hibernate.orm.jdbc.bind: trace #스프링 부트 3.x, hibernate6
